#!/bin/bash

# Definir cores
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
MAGENTA="\033[1;35m"
CYAN="\033[1;36m"
RESET="\033[0m"

FILE_FOLDER=$(dirname $0)

# Remover ficheiros de testes passados
echo $'\n'
echo -e "${YELLOW}Remover ficheiros e pastas de testes passados${RESET}"

if test -f "${FILE_FOLDER}/Subject_A_keys.json"; then
    rm "${FILE_FOLDER}/Subject_A_keys.json"
    echo "--> Ficheiro '"${FILE_FOLDER}/Subject_A_keys.json"' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/Subject_B_keys.json"; then
    rm "${FILE_FOLDER}/Subject_B_keys.json"
    echo "--> Ficheiro '"${FILE_FOLDER}/Subject_B_keys.json"' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/Subject_A_session.json"; then
    rm "${FILE_FOLDER}/Subject_A_session.json"
    echo "--> Ficheiro '"${FILE_FOLDER}/Subject_A_session.json"' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/Subject_B_session.json"; then
    rm "${FILE_FOLDER}/Subject_B_session.json"
    echo "--> Ficheiro '"${FILE_FOLDER}/Subject_B_session.json"' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/rep_pub_key.pem"; then
    rm "${FILE_FOLDER}/rep_pub_key.pem"
    echo "--> Ficheiro '"${FILE_FOLDER}/rep_pub_key.pem"' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/test_file_10Kb"; then
    rm "${FILE_FOLDER}/test_file_10Kb"
    echo "--> Ficheiro '${FILE_FOLDER}/test_file_10Kb' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/test_file_100Kb"; then
    rm "${FILE_FOLDER}/test_file_100Kb"
    echo "--> Ficheiro '${FILE_FOLDER}/test_file_100Kb' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/test_file_1Mb"; then
    rm "${FILE_FOLDER}/test_file_1Mb"
    echo "--> Ficheiro '${FILE_FOLDER}/test_file_1Mb' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/small_story.txt"; then
    rm "${FILE_FOLDER}/small_story.txt"
    echo "--> Ficheiro '${FILE_FOLDER}/small_story.txt' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/metadados.json"; then
    rm "${FILE_FOLDER}/metadados.json"
    echo "--> Ficheiro '${FILE_FOLDER}/metadados.json' removido."
    sleep 0.1
fi

if test -d "${FILE_FOLDER}/repository/docs"; then
    rm -rf "${FILE_FOLDER}/repository/docs"
    echo "--> Pasta '${FILE_FOLDER}/repository/docs' removida."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/repository/documents.json"; then
    rm "${FILE_FOLDER}/repository/documents.json"
    echo "--> Ficheiro '${FILE_FOLDER}/repository/documents.json' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/repository/organizations.json"; then
    rm "${FILE_FOLDER}/repository/organizations.json"
    echo "--> Ficheiro '${FILE_FOLDER}/repository/organizations.json' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/repository/sessions.json"; then
    rm "${FILE_FOLDER}/repository/sessions.json"
    echo "--> Ficheiro '${FILE_FOLDER}/repository/sessions.json' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/repository/rep_priv_key.pem"; then
    rm "${FILE_FOLDER}/repository/rep_priv_key.pem"
    echo "--> Ficheiro '${FILE_FOLDER}/repository/rep_priv_key.pem' removido."
    sleep 0.1
fi

if test -f "${FILE_FOLDER}/repository/rep_pub_key.pem"; then
    rm "${FILE_FOLDER}/repository/rep_pub_key.pem"
    echo "--> Ficheiro '${FILE_FOLDER}/repository/rep_pub_key.pem' removido."
    sleep 0.1
fi
echo $'\n'
