#!/bin/bash

default_path="../client.py" 

if [ -f $default_path ]; then
    :
elif [ -f "/.dockerenv" ]; then
    default_path="/client/client.py"
else
    echo "[ERROR] Couldn't find the client.py file."
    exit 1
fi

# rep_acl_doc <session file> <document name> [+/-] <role> <permission>
python3 "$default_path" -c rep_acl_doc $1 $2 $3 $4 $5;
