#!/bin/bash

default_path="../client.py" 

if [ -f $default_path ]; then
    :
elif [ -f "/.dockerenv" ]; then
    default_path="/client/client.py"
else
    echo "[ERROR] Couldn't find the client.py file."
    exit 1
fi

# rep_add_subject <session file> <username> <name> <email> <credentials file>
python3 "$default_path" -c rep_add_subject $1 $2 $3 $4 $5
