#!/bin/bash

default_path="../client.py" 

if [ -f $default_path ]; then
    :
elif [ -f "/.dockerenv" ]; then
    default_path="/client/client.py"
else
    echo "[ERROR] Couldn't find the client.py file."
    exit 1
fi

# rep_list_subjects <session file> [username]
if [ -z "$2" ]; then
    python3 "$default_path" -c rep_list_subjects "$1"
else
    python3 "$default_path" -c rep_list_subjects "$1" "$2"
fi