#!/bin/bash

default_path="../client.py" 

if [ -f $default_path ]; then
    :
elif [ -f "/.dockerenv" ]; then
    default_path="/client/client.py"
else
    echo "[ERROR] Couldn't find the client.py file."
    exit 1
fi

# rep_remove_permission <session file> <role> <username/permission>
python3 "$default_path" -c rep_remove_permission $1 $2 $3