#!/bin/bash

# rep_list_docs <session file> [-s username] [-d nt/ot/et date]
default_path="../client.py" 

if [ -f $default_path ]; then
    :
elif [ -f "/.dockerenv" ]; then
    default_path="/client/client.py"
else
    echo "[ERROR] Couldn't find the client.py file."
    exit 1
fi

SESSION_FILE="$1"
shift # Remove the session file from arguments

# Base command
CMD="python3 $default_path -c rep_list_docs $SESSION_FILE"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -s) # Username flag
            CMD+=" -s $2"
            shift 2
            ;;
        -d) # Date flag with 2 arguments
            CMD+=" -d $2 $3"
            shift 3
            ;;
        *) # Unrecognized arguments
            echo "Unknown argument: $1"
            exit 1
            ;;
    esac
done

# Execute the constructed command
eval "$CMD"
