#!/bin/bash

default_path="../client.py" 

if [ -f $default_path ]; then
    :
elif [ -f "/.dockerenv" ]; then
    default_path="/client/client.py"
else
    echo "[ERROR] Couldn't find the client.py file."
    exit 1
fi

if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ $1 = "--help" ]); then
  bold=$(tput bold)
  normal=$(tput sgr0)
  dim=$(tput dim 2>/dev/null || echo "")
  echo -e "
  ${bold}Usage: rep_subject_credentials <password> <output_file>${normal}
    ${dim}The argument <password> will be used to encrypt the private key, so you must remember it.
    The argument <output_file> will be where the keys will be stored.${normal}
  "
  exit 0
fi

# rep_subject_credentials <password> <credentials_file>
python3 "$default_path" -c rep_subject_credentials $1 $2
